#!/usr/bin/env python3
"""Draw the PLACEHOLDER art: frosted-glass shapes on midnight navy.

These stand in until the AI pictures from tools/art/PROMPTS.md are made.
They are drawn here from shapes, not generated by a model, so they carry no
model licence. Each one is written as a source PNG to the folder given, then
run through build_art.py, which writes the sizes the pages use.

    python3 tools/art/placeholder_art.py /tmp/art-src
"""
import math
import os
import random
import subprocess
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
NAVY_TOP = (6, 11, 28)
NAVY_BOT = (12, 22, 54)
MINT = (159, 240, 208)
PERI = (142, 162, 255)


def backdrop(w, h, glows, seed):
    rnd = random.Random(seed)
    im = Image.new("RGB", (w, h))
    d = ImageDraw.Draw(im)
    for y in range(h):
        t = y / max(1, h - 1)
        d.line([(0, y), (w, y)], fill=tuple(int(a + (b - a) * t) for a, b in zip(NAVY_TOP, NAVY_BOT)))
    for (cx, cy, r, col, a) in glows:
        layer = Image.new("RGB", (w, h), (0, 0, 0))
        mask = Image.new("L", (w, h), 0)
        # Glows are a soft light in the dark, not a wash: about a third of
        # the given strength at the centre, fading to nothing at the edge.
        ImageDraw.Draw(mask).ellipse((cx * w - r * w, cy * h - r * w, cx * w + r * w, cy * h + r * w), fill=int(255 * a * 0.6))
        mask = mask.filter(ImageFilter.GaussianBlur(r * w * 0.6))
        layer.paste(col, (0, 0, w, h))
        im = Image.composite(layer, im, mask)
    # A little grain so the gradients do not band once compressed.
    # effect_noise is centred on 128, so take 128 back off.
    noise = Image.effect_noise((w, h), 5).convert("RGB")
    im = ImageChops.add(im, noise, scale=1.0, offset=-128)
    _ = rnd
    return im


def glass(im, shape_mask, tint=(255, 255, 255), fill_a=0.07, edge_a=0.42, blur=18):
    """Frost what is behind shape_mask, tint it, and draw a lit edge."""
    w, h = im.size
    frosted = im.filter(ImageFilter.GaussianBlur(blur))
    frosted = Image.blend(frosted, Image.new("RGB", (w, h), tint), fill_a)
    im = Image.composite(frosted, im, shape_mask)
    edge = shape_mask.filter(ImageFilter.FIND_EDGES).filter(ImageFilter.MaxFilter(3))
    # Light from the top: the upper edge is brighter than the lower one.
    grad = Image.linear_gradient("L").resize((w, h)).point(lambda v: 255 - v)
    edge = ImageChops.multiply(edge, grad.point(lambda v: int(v * edge_a)))
    im = Image.composite(Image.new("RGB", (w, h), (235, 255, 248)), im, edge)
    return im


def rrect_mask(w, h, box, radius, angle=0.0):
    m = Image.new("L", (w * 2, h * 2), 0)
    x0, y0, x1, y1 = [v * 2 for v in box]
    ImageDraw.Draw(m).rounded_rectangle((x0, y0, x1, y1), radius=radius * 2, fill=255)
    if angle:
        cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
        m = m.rotate(angle, resample=Image.BICUBIC, center=(cx, cy))
    return m.resize((w, h), Image.LANCZOS)


def poly_mask(w, h, pts):
    m = Image.new("L", (w * 2, h * 2), 0)
    ImageDraw.Draw(m).polygon([(x * 2, y * 2) for x, y in pts], fill=255)
    return m.resize((w, h), Image.LANCZOS)


def ellipse_mask(w, h, box):
    m = Image.new("L", (w * 2, h * 2), 0)
    ImageDraw.Draw(m).ellipse([v * 2 for v in box], fill=255)
    return m.resize((w, h), Image.LANCZOS)


def dot(im, x, y, r, col, glow=3.0):
    w, h = im.size
    m = ellipse_mask(w, h, (x - r * glow, y - r * glow, x + r * glow, y + r * glow)).filter(ImageFilter.GaussianBlur(r * 1.5))
    im = Image.composite(Image.new("RGB", (w, h), col), im, m.point(lambda v: int(v * 0.55)))
    return Image.composite(Image.new("RGB", (w, h), col), im, ellipse_mask(w, h, (x - r, y - r, x + r, y + r)))


def orb(im, x, y, r):
    w, h = im.size
    im = glass(im, ellipse_mask(w, h, (x - r, y - r, x + r, y + r)), fill_a=0.10, edge_a=0.6, blur=10)
    return dot(im, x - r * 0.35, y - r * 0.35, max(2, r * 0.12), (240, 255, 250), glow=2.2)


def hero(w, h, seed):
    im = backdrop(w, h, [(0.78, 0.18, 0.42, MINT, 0.42), (0.12, 0.85, 0.5, PERI, 0.36), (0.5, 0.55, 0.3, (60, 90, 200), 0.25)], seed)
    s = min(w, h)
    tall = h > w
    panels = [
        (0.58, 0.16, 0.36, 0.42, -12), (0.66, 0.36, 0.30, 0.38, 8), (0.08, 0.62, 0.30, 0.30, 10)
    ] if not tall else [
        (0.40, 0.08, 0.58, 0.30, -10), (0.52, 0.26, 0.46, 0.26, 7), (0.02, 0.72, 0.50, 0.22, 9)
    ]
    for (px, py, pw, ph, ang) in panels:
        box = (px * w, py * h, (px + pw) * w, (py + ph) * h)
        im = glass(im, rrect_mask(w, h, box, s * 0.04, ang), blur=int(s * 0.03))
    for (ox, oy, orr) in ([(0.86, 0.72, 0.05), (0.30, 0.22, 0.025), (0.46, 0.80, 0.018)] if not tall else
                          [(0.80, 0.62, 0.07), (0.18, 0.30, 0.035), (0.62, 0.90, 0.03)]):
        im = orb(im, ox * w, oy * h, orr * s * (1.6 if tall else 1.0))
    return im


def servers(w, h, seed):
    im = backdrop(w, h, [(0.7, 0.2, 0.45, MINT, 0.38), (0.2, 0.9, 0.45, PERI, 0.32)], seed)
    for i in range(3):
        y0 = h * (0.2 + i * 0.22)
        box = (w * 0.24, y0, w * 0.76, y0 + h * 0.17)
        im = glass(im, rrect_mask(w, h, box, h * 0.035), blur=14)
        for j in range(3):
            im = dot(im, w * (0.30 + j * 0.035), y0 + h * 0.085, h * 0.012, MINT if j < 2 else PERI)
        d = ImageDraw.Draw(im)
        for k in range(4):
            x = w * (0.48 + k * 0.06)
            d.rounded_rectangle((x, y0 + h * 0.07, x + w * 0.04, y0 + h * 0.10), radius=3, fill=(46, 62, 110))
    return im


def bots(w, h, seed):
    im = backdrop(w, h, [(0.25, 0.25, 0.42, PERI, 0.36), (0.8, 0.85, 0.45, MINT, 0.38)], seed)
    box = (w * 0.26, h * 0.18, w * 0.74, h * 0.70)
    m = rrect_mask(w, h, box, h * 0.09)
    tail = poly_mask(w, h, [(w * 0.34, h * 0.66), (w * 0.30, h * 0.84), (w * 0.44, h * 0.68)])
    im = glass(im, ImageChops.lighter(m, tail), blur=16)
    plane = poly_mask(w, h, [(w * 0.40, h * 0.46), (w * 0.62, h * 0.32), (w * 0.55, h * 0.58), (w * 0.50, h * 0.50)])
    im = Image.composite(Image.new("RGB", (w, h), MINT), im, plane.point(lambda v: int(v * 0.9)))
    im = orb(im, w * 0.82, h * 0.26, h * 0.06)
    return im


def tools(w, h, seed):
    im = backdrop(w, h, [(0.5, 0.15, 0.4, MINT, 0.36), (0.15, 0.8, 0.4, PERI, 0.34)], seed)
    cx, cy, r = w * 0.5, h * 0.48, h * 0.30
    hexa = [(cx + r * math.cos(math.radians(a)), cy + r * math.sin(math.radians(a))) for a in range(30, 390, 60)]
    im = glass(im, poly_mask(w, h, hexa), blur=16)
    lens = (cx - r * 0.45, cy - r * 0.45, cx + r * 0.45, cy + r * 0.45)
    im = glass(im, ellipse_mask(w, h, lens), tint=MINT, fill_a=0.18, edge_a=0.7, blur=6)
    beam = poly_mask(w, h, [(cx + r * 0.3, cy + r * 0.3), (w * 0.95, h * 0.95), (w * 0.82, h * 1.0)]).filter(ImageFilter.GaussianBlur(6))
    im = Image.composite(Image.new("RGB", (w, h), MINT), im, beam.point(lambda v: int(v * 0.35)))
    return im


def plumb(w, h, seed):
    im = backdrop(w, h, [(0.5, 0.0, 0.5, MINT, 0.34), (0.85, 0.9, 0.4, PERI, 0.34)], seed)
    d = ImageDraw.Draw(im)
    d.line([(w * 0.5, 0), (w * 0.5, h * 0.36)], fill=(190, 250, 228), width=max(2, w // 400))
    bob = [(w * 0.5, h * 0.36), (w * 0.60, h * 0.52), (w * 0.5, h * 0.86), (w * 0.40, h * 0.52)]
    im = glass(im, poly_mask(w, h, bob), blur=14, edge_a=0.6)
    core = [(w * 0.5, h * 0.47), (w * 0.535, h * 0.56), (w * 0.5, h * 0.70), (w * 0.465, h * 0.56)]
    im = Image.composite(Image.new("RGB", (w, h), MINT), im, poly_mask(w, h, core).filter(ImageFilter.GaussianBlur(3)))
    im = glass(im, rrect_mask(w, h, (w * 0.08, h * 0.88, w * 0.92, h * 0.94), h * 0.03), blur=10)
    return im


def quay(w, h, seed):
    im = backdrop(w, h, [(0.5, 0.42, 0.35, MINT, 0.30), (0.1, 0.1, 0.4, PERI, 0.30)], seed)
    hz = h * 0.42
    d = ImageDraw.Draw(im)
    for i in range(14):
        y = hz + (h - hz) * (i / 14) ** 1.6 + 4
        a = 40 + i * 6
        d.line([(w * 0.04, y), (w * 0.96, y)], fill=(a // 2, a, a + 30), width=1)
    pier = [(w * 0.47, hz), (w * 0.53, hz), (w * 0.80, h), (w * 0.20, h)]
    im = glass(im, poly_mask(w, h, pier), blur=12, edge_a=0.55)
    im = dot(im, w * 0.5, hz - h * 0.03, h * 0.022, MINT, glow=4)
    refl = poly_mask(w, h, [(w * 0.495, hz + 6), (w * 0.505, hz + 6), (w * 0.52, h * 0.7), (w * 0.48, h * 0.7)]).filter(ImageFilter.GaussianBlur(4))
    im = Image.composite(Image.new("RGB", (w, h), MINT), im, refl.point(lambda v: int(v * 0.4)))
    return im


JOBS = [
    ("hero-wide", hero, (1920, 1080)),
    ("hero-tall", hero, (900, 1200)),
    ("svc-servers", servers, (1200, 750)),
    ("svc-bots", bots, (1200, 750)),
    ("svc-tools", tools, (1200, 750)),
    ("plumb", plumb, (1200, 750)),
    ("quay", quay, (1200, 750)),
    ("og-home", hero, (1200, 630)),
    ("og-plumb", plumb, (1200, 630)),
    ("og-quay", quay, (1200, 630)),
]


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    out = argv[1]
    os.makedirs(out, exist_ok=True)
    for i, (name, fn, (w, h)) in enumerate(JOBS):
        src = os.path.join(out, name + ".png")
        fn(w, h, 35 + i).save(src)
        subprocess.check_call([sys.executable, os.path.join(HERE, "build_art.py"), name, src])
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
